### ISSUE TITLE
Make docs easily accessible

### ISSUE THREAD

**Issue by jacobgasser** [discordjs/website#82]
**Is your feature request related to a problem? Please describe.**
I find it difficult when typing in the entire link to get to the docs, I wish there was a simpler way to access them.

**Describe the ideal solution**
Redirect users who go to "https://discord.js.org/docs" to the latest stable docs ("https://discord.js.org/#/docs/main/stable/general/welcome")

**Comment by Poly-Pixel** [comment]
> i mean, we could deploy a `docs.html` with `<meta http-equiv="refresh" content="0; url=https://discord.js.org/#/docs">` so that `https://discord.js.org/docs` works

Not sure how much this is really needed, but something like this might be nice. It's not like going to https://discord.js.org/docs breaks the website, it just redirects you to the home page where you can easily see the link for documentation. If you're visiting the documentation a lot, you can just bookmark https://discord.js.org/#/docs. 

> Also how about replacing main page as document's main page, always taking seconds with clicking docs button. Just / is enough for viewing docs. How about this?

I don't think that this is a very good idea, as first-time visitors would be dropped straight into the documentation, without an idea of what discord.js does exactly.

**Comment by seia-soto** [comment]
> > 나는 우리가를 배포 할 수있는, 의미 `docs.html`와 `<meta http-equiv="refresh" content="0; url=https://discord.js.org/#/docs">`그래서 `https://discord.js.org/docs`작품
> 
> 이것이 실제로 얼마나 필요한지 확실하지 않지만 이와 같은 것이 좋을 수 있습니다. [https://discord.js.org/docs로](https://discord.js.org/docs) 이동하는 것이 웹 사이트를 망가 뜨리는 것과는 달리 문서 링크를 쉽게 볼 수있는 홈페이지로 리디렉션됩니다. 문서를 많이 방문하는 경우 [https://discord.js.org/#/docs를](https://discord.js.org/#/docs) 북마크하기 만하면 됩니다.
> 
> > 또한 문서 버튼을 클릭하면 항상 몇 초만에 문서의 기본 페이지로 기본 페이지를 교체하는 방법도 있습니다. 문서를 보려면 /만으로 충분합니다. 이건 어때요?
> 
> 처음 방문하는 사람은 discord.js가 정확히 무엇을하는지 알지 못한 채 문서로 바로 들어가기 때문에 이것이별로 좋은 생각이라고 생각하지 않습니다.

This is an old issue and my opinion changed a bit after typing that comment on this issue thread as I grow.

When I commented first time on this issue, I think clicking the `Docs` button on Discord.JS website is really annoying because layout of website shifts a lot. Also, font size was too small to read easily. (Now, I think that readability was the most problematic part when I commented)

Now, I don't think that this opinion would be powerful because the problematic part of documentation disappeared after design changed.

So that's what my opinion changed and below is my current thoughts about your opinion. (I am emotionally tired a bit but really don't want to fight, so don't think me as your opponent. I am little bit worried about this while writing and reading my comment. I am here to enhance Discord.JS.)

First of all, maybe there are someone can't, but I think most of us can understand what Discord.JS does. However, I understand the part of us that can't understand what Discord.JS does. Also, I think I can be one of someone who cannot understand if I didn't do JavaScript before.

So, I want to answer with better choice that I thought to reduce layout shift. First of all, I suggest that enhancing welcome page of documentation side of website, so we can select docs we need more easily without clicking one more.

That's my opinion if I enhace the website a bit more.

However, I don't think current website is uncomfortable or low in readability.

> Most of part of my comment was written based on my environment. Really sorry about I am emotionally tired today. So, please consider only the main part of my comment.

**Comment by seia-soto** [comment]
Also, I think the community should change a bit at least if there are group of someone that saying this is uncomfortable. I also partly agree with your comment.

**Comment by Poly-Pixel** [comment]
>  First of all, I suggest that enhancing welcome page of documentation side of website, so we can select docs we need more easily without clicking one more.

What exactly do you mean by “enhancing”?

> However, I don’t think that the current website is uncomfortable or low in readability.

I agree with this for the most part. However, when I first got started with Discord.js, I was a little confused about how the docs were organized. If the website is going to be changed, I think that a small paragraph explaining how the docs are organized and how to navigate them might be helpful to people visiting the docs for the first time.

**Comment by seia-soto** [comment]
> > First of all, I suggest that enhancing welcome page of documentation side of website, so we can select docs we need more easily without clicking one more.
> 
> What exactly do you mean by “enhancing”?
> 
> > However, I don’t think that the current website is uncomfortable or low in readability.
> 
> I agree with this for the most part. However, when I first got started with Discord.js, I was a little confused about how the docs were organized. If the website is going to be changed, I think that a small paragraph explaining how the docs are organized and how to navigate them might be helpful to people visiting the docs for the first time.

I mean that merging main page of Discord.js docs into Welcome page of documentation section would be nice. I think Welcome page is also pretty nice for first comers and existing users don't need to click one more time to see docs at the time.

![image](https://user-images.githubusercontent.com/30369714/125013858-888c7a00-e0a7-11eb-8d1a-a10024f0050c.png)

**Comment by iCrawl** [comment]
Things will stay as-is 👍
